image: node:latest

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - cd front-end

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

build-job:
  stage : build
  script:
    - npm install
    - npm run build

test-job:
  stage: test
  script:
    - npm install
    - CI=true npm test

deploy-to-heroku:
  stage: deploy
  script: 
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
