image: node:latest

before_script:
  - cd frontend

stages:
  - build
  - test
  - server
  - deploy

cache:
  paths:
    - node_modules/

build-job:
  stage: build
  script:
    - yarn install
    - yarn run build
  needs: []

test-job:
  stage: test
  script:
    - yarn install
    - CI=true yarn test
  needs: []

stage-server:
  stage: server
  before_script: []
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_SERVER_NAME --api-key=$HEROKU_API_KEY

deploy-to-heroku:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  needs: [build-job, test-job]
