const data = [
  {
    id: 0,
    projectId: 0,
    leader: "Jason Bourne",
    maxMembers: 5,
    teammates: ["Ayoob Patel", "Alex Duku", "Jaimi Ajmeera"],
    requirements: {
      "Code Language": "Java",
      Timezone: 1,
      "Spoken Language": "English",
    },
    adRequirements: "Willing to work in person",
  },
  {
    id: 1,
    projectId: 0,
    leader: "Alice Ecila",
    maxMembers: 5,
    teammates: ["Jeff Jeffery", "Harry Arnold"],
    requirements: {
      "Code Language": "Haskell",
      Timezone: 1,
      "Spoken Language": "Spanish",
    },
    adRequirements: "Proficient in discord",
  },
  {
    id: 5,
    projectId: 0,
    leader: "Edward Daniels",
    maxMembers: 3,
    teammates: [],
    requirements: {
      "Code Language": "Haskell",
      Timezone: 1,
      "Spoken Language": "English",
    },
    adRequirements: "",
  },
  {
    id: 6,
    projectId: 0,
    leader: "Helen Samuel",
    maxMembers: 4,
    teammates: ["Hassan Ahmed"],
    requirements: {
      "Code Language": "C",
      Timezone: 1,
      "Spoken Language": "English",
    },
    adRequirements: "Proficient in designing UI",
  },
  {
    id: 3,
    projectId: 1,
    leader: "Steve Stevenson",
    maxMember: 4,
    teammates: [],
    requirements: {
      "Code Language": "PHP",
      Timezone: -5,
      "Spoken Language": "English",
    },
    adRequirements: "Knowledge in back end technologies",
  },
  {
    id: 7,
    projectId: 1,
    leader: "William Arnold",
    maxMember: 4,
    teammates: ["James Ellis"],
    requirements: {
      "Code Language": "WACC",
      Timezone: 1,
      "Spoken Language": "English",
    },
    adRequirements: "",
  },
  {
    id: 8,
    projectId: 1,
    leader: "Ali Jassam",
    maxMember: 4,
    teammates: ["Eli Jackson, Micheal Henderson"],
    requirements: {
      "Code Language": "Java",
      Timezone: 1,
      "Spoken Language": "English",
    },
    adRequirements: "",
  },
  {
    id: 4,
    projectId: 2,
    leader: "Jeff Wetherspoon",
    remaining: 2,
    teammates: ["Ellie Lin", "Mohammed Abdi"],
    requirements: {
      "Code Language": "JavaScript",
      Timezone: 1,
      "Spoken Language": "English",
    },
    adRequirements: "",
  },
  {
    id: 9,
    projectId: 2,
    leader: "Glen Mount",
    remaining: 2,
    teammates: ["Reece Christensen"],
    requirements: {
      "Code Language": "Python",
      Timezone: 1,
      "Spoken Language": "English",
    },
    adRequirements: "",
  },
  {
    id: 10,
    projectId: 2,
    leader: "Jadon Font",
    remaining: 2,
    teammates: ["Barry Ali"],
    requirements: {
      "Code Language": "C++",
      Timezone: 1,
      "Spoken Language": "English",
    },
    adRequirements: "Available for at least 6 hours a day",
  },
];

export default data;
